[package]
name = "dumo-backends"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Ripping backend adapters for dump-o-matic"

[dependencies]
dumo-core = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
