//! Filesystem operations that uphold the project's data-safety invariant.
//!
//! > No source is deleted until its replacement is verified by checksum on a genuine
//! > re-read at the destination.
//!
//! Two mechanisms, chosen by circumstance:
//!
//! - **Same filesystem:** `rename(2)`. Atomic, moves no data, and the file keeps its
//!   inode — there is no window in which the content could be lost or corrupted, and
//!   nothing is deleted. Re-hashing afterwards would verify nothing that the operation
//!   did not already guarantee.
//! - **Across filesystems:** copy to a temporary name, flush to disk, **re-read and
//!   hash**, and only then rename into place and remove the source. The temporary name
//!   matters: an interrupted copy must never leave a truncated file sitting at the real
//!   destination path, where a later run would mistake it for complete.

use crate::hash;
use std::path::{Path, PathBuf};

#[derive(Debug, thiserror::Error)]
pub enum FsError {
    #[error("destination {path} already exists; refusing to overwrite")]
    DestinationExists { path: PathBuf },

    #[error("source {path} does not exist")]
    SourceMissing { path: PathBuf },

    #[error("verification failed for {path}: expected {expected}, got {actual}")]
    VerificationFailed {
        path: PathBuf,
        expected: String,
        actual: String,
    },

    #[error("i/o error on {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

type Result<T> = std::result::Result<T, FsError>;

/// How a move was carried out.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MoveMethod {
    /// Atomic rename within one filesystem; no data was copied.
    Rename,
    /// Copied to another filesystem and verified by re-reading the destination.
    CopyVerified,
}

/// Outcome of a verified move.
#[derive(Debug, Clone)]
pub struct MoveOutcome {
    pub method: MoveMethod,
    pub bytes: u64,
    /// Hash confirmed by re-reading the destination, when a copy was performed.
    pub verified_sha256: Option<String>,
}

fn io_err(path: &Path) -> impl FnOnce(std::io::Error) -> FsError + '_ {
    move |source| FsError::Io {
        path: path.to_path_buf(),
        source,
    }
}

/// Move a file, never overwriting and never losing data.
///
/// `expected_sha256` is compared against the destination after a cross-filesystem copy.
/// When `None`, the source is hashed first so there is still something to verify against.
pub fn move_verified(src: &Path, dest: &Path, expected_sha256: Option<&str>) -> Result<MoveOutcome> {
    if !src.is_file() {
        return Err(FsError::SourceMissing {
            path: src.to_path_buf(),
        });
    }
    // Never clobber. This is checked before every write path below, and again by using
    // create_new when the copy path opens the destination.
    if dest.exists() {
        return Err(FsError::DestinationExists {
            path: dest.to_path_buf(),
        });
    }
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent).map_err(io_err(parent))?;
    }

    let bytes = std::fs::metadata(src).map_err(io_err(src))?.len();

    match std::fs::rename(src, dest) {
        Ok(()) => Ok(MoveOutcome {
            method: MoveMethod::Rename,
            bytes,
            verified_sha256: None,
        }),
        // EXDEV: different filesystems, so the content has to be copied.
        Err(e) if e.raw_os_error() == Some(libc::EXDEV) => {
            let expected = match expected_sha256 {
                Some(h) => h.to_string(),
                None => hash::sha256_file(src).map_err(io_err(src))?.0,
            };
            let verified = copy_verified(src, dest, &expected)?;
            // Only now is it safe to remove the source.
            std::fs::remove_file(src).map_err(io_err(src))?;
            Ok(MoveOutcome {
                method: MoveMethod::CopyVerified,
                bytes,
                verified_sha256: Some(verified),
            })
        }
        Err(e) => Err(FsError::Io {
            path: dest.to_path_buf(),
            source: e,
        }),
    }
}

/// Write generated bytes to a new file and prove what landed on disk matches.
///
/// Used for artifacts that are reconstructed rather than copied — a Redump-canonical
/// `.cue` sheet, for instance, which names its track files and so has to be rebuilt when
/// those files take their archival names. Such a file has no source to move, but it must
/// meet the same bar as one that does: never clobber, and never claim success without
/// reading the result back.
///
/// `expected_sha256` is checked against the *bytes as read back from disk*, so a
/// truncated or mangled write fails rather than being recorded as verified. Returns the
/// hash read back.
pub fn write_verified(dest: &Path, contents: &[u8], expected_sha256: &str) -> Result<String> {
    if dest.exists() {
        return Err(FsError::DestinationExists {
            path: dest.to_path_buf(),
        });
    }
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent).map_err(io_err(parent))?;
    }

    // Write to a sibling temp first: a failure part-way through must not leave anything
    // at the real path, where a later run would treat it as a finished artifact.
    let tmp = temp_sibling(dest);
    let write = || -> std::io::Result<()> {
        use std::io::Write;
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&tmp)?;
        f.write_all(contents)?;
        f.sync_all()
    };
    if let Err(e) = write() {
        std::fs::remove_file(&tmp).ok();
        return Err(FsError::Io {
            path: tmp,
            source: e,
        });
    }

    // Read back from disk rather than hashing the buffer we already hold; hashing our
    // own memory would prove nothing about what was actually stored.
    let actual = match hash_evicting(&tmp) {
        Ok(h) => h,
        Err(e) => {
            std::fs::remove_file(&tmp).ok();
            return Err(FsError::Io { path: tmp, source: e });
        }
    };
    if actual != expected_sha256 {
        std::fs::remove_file(&tmp).ok();
        return Err(FsError::VerificationFailed {
            path: dest.to_path_buf(),
            expected: expected_sha256.to_string(),
            actual,
        });
    }

    std::fs::rename(&tmp, dest).map_err(io_err(dest))?;
    Ok(actual)
}

/// Copy a file and prove the destination matches, leaving the source untouched.
///
/// Returns the hash read back from the destination. On any failure the partial file is
/// removed and the real destination path is never created.
pub fn copy_verified(src: &Path, dest: &Path, expected_sha256: &str) -> Result<String> {
    if dest.exists() {
        return Err(FsError::DestinationExists {
            path: dest.to_path_buf(),
        });
    }
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent).map_err(io_err(parent))?;
    }

    // Write to a temporary sibling so an interruption cannot leave a truncated file at
    // the destination path.
    let tmp = temp_sibling(dest);
    let _ = std::fs::remove_file(&tmp);

    let copy_result = (|| -> std::io::Result<()> {
        use std::io::{Read, Write};
        let mut input = std::fs::File::open(src)?;
        let mut output = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&tmp)?;

        let mut buf = vec![0u8; 1024 * 1024];
        loop {
            let n = input.read(&mut buf)?;
            if n == 0 {
                break;
            }
            output.write_all(&buf[..n])?;
        }
        // Flush our buffers and ask the filesystem to commit before we read back.
        output.flush()?;
        output.sync_all()?;
        // Evict what we just wrote, so the verification read has to fetch it again.
        drop_page_cache(&output);
        Ok(())
    })();

    if let Err(e) = copy_result {
        let _ = std::fs::remove_file(&tmp);
        return Err(FsError::Io {
            path: tmp,
            source: e,
        });
    }

    // Re-read the written file and hash it. A fresh handle after sync_all and a page
    // cache eviction is what makes this a genuine verification rather than a re-hash of
    // our own buffers.
    //
    // Caveat, stated plainly: POSIX_FADV_DONTNEED is advisory, and a network filesystem
    // may still satisfy the read locally. This is a strong check, not an absolute proof
    // of server-side durability.
    let actual = match hash_evicting(&tmp) {
        Ok(h) => h,
        Err(e) => {
            let _ = std::fs::remove_file(&tmp);
            return Err(FsError::Io { path: tmp, source: e });
        }
    };

    if actual != expected_sha256 {
        let _ = std::fs::remove_file(&tmp);
        return Err(FsError::VerificationFailed {
            path: dest.to_path_buf(),
            expected: expected_sha256.to_string(),
            actual,
        });
    }

    std::fs::rename(&tmp, dest).map_err(io_err(dest))?;
    Ok(actual)
}

/// Hash a file after evicting it from the page cache, so the read reaches storage.
pub fn hash_evicting(path: &Path) -> std::io::Result<String> {
    {
        // Evict before reading, in case anything cached it since it was written.
        let f = std::fs::File::open(path)?;
        drop_page_cache(&f);
    }
    let (h, _) = hash::sha256_file(path)?;
    Ok(h)
}

/// Ask the kernel to drop this file's pages from the page cache.
///
/// This is what turns the post-copy re-read into a real verification. Without it, the
/// read after a write is very likely served from local RAM — so we would be hashing our
/// own buffers and proving nothing about what reached the disk or the server. That
/// matters most on network filesystems, where "the write succeeded" is the weakest.
///
/// `POSIX_FADV_DONTNEED` needs no privileges. It is advisory: the kernel may decline, so
/// this strengthens the check without being something to rely on absolutely.
fn drop_page_cache(file: &std::fs::File) {
    use std::os::unix::io::AsRawFd;
    unsafe {
        // offset 0, len 0 means "the whole file".
        libc::posix_fadvise(file.as_raw_fd(), 0, 0, libc::POSIX_FADV_DONTNEED);
    }
}

/// A temporary path beside `dest`, so the rename into place stays within one directory.
fn temp_sibling(dest: &Path) -> PathBuf {
    let name = dest
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "file".into());
    dest.with_file_name(format!(".{name}.dumo-partial"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn scratch(name: &str) -> PathBuf {
        let mut p = std::env::temp_dir();
        p.push(format!("dumo-fsops-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&p);
        std::fs::create_dir_all(&p).unwrap();
        p
    }

    fn write(path: &Path, content: &[u8]) {
        if let Some(p) = path.parent() {
            std::fs::create_dir_all(p).unwrap();
        }
        std::fs::File::create(path).unwrap().write_all(content).unwrap();
    }

    #[test]
    fn moves_within_a_filesystem_by_rename() {
        let dir = scratch("rename");
        let src = dir.join("a.iso");
        let dest = dir.join("sub/b.iso");
        write(&src, b"hello world");

        let out = move_verified(&src, &dest, None).unwrap();
        assert_eq!(out.method, MoveMethod::Rename);
        assert_eq!(out.bytes, 11);
        assert!(!src.exists(), "source should be gone after a move");
        assert_eq!(std::fs::read(&dest).unwrap(), b"hello world");
        std::fs::remove_dir_all(dir).ok();
    }

    /// The single most important behaviour: never destroy an existing file.
    #[test]
    fn refuses_to_overwrite_an_existing_destination() {
        let dir = scratch("nooverwrite");
        let src = dir.join("a.iso");
        let dest = dir.join("b.iso");
        write(&src, b"new content");
        write(&dest, b"PRECIOUS EXISTING DATA");

        let err = move_verified(&src, &dest, None).unwrap_err();
        assert!(matches!(err, FsError::DestinationExists { .. }));
        // Both files must survive untouched.
        assert_eq!(std::fs::read(&dest).unwrap(), b"PRECIOUS EXISTING DATA");
        assert_eq!(std::fs::read(&src).unwrap(), b"new content");
        std::fs::remove_dir_all(dir).ok();
    }

    #[test]
    fn missing_source_is_an_error() {
        let dir = scratch("nosrc");
        let err = move_verified(&dir.join("nope"), &dir.join("dest"), None).unwrap_err();
        assert!(matches!(err, FsError::SourceMissing { .. }));
        std::fs::remove_dir_all(dir).ok();
    }

    #[test]
    fn copy_verified_writes_and_confirms() {
        let dir = scratch("copyok");
        let src = dir.join("a.bin");
        let dest = dir.join("out/a.bin");
        write(&src, b"verify me");

        let expected = hash::sha256_file(&src).unwrap().0;
        let got = copy_verified(&src, &dest, &expected).unwrap();
        assert_eq!(got, expected);
        assert_eq!(std::fs::read(&dest).unwrap(), b"verify me");
        // Source is left alone; only move_verified removes it, and only after this.
        assert!(src.exists());
        std::fs::remove_dir_all(dir).ok();
    }

    /// A mismatch must leave no destination file and no stray partial.
    #[test]
    fn copy_verified_rejects_a_hash_mismatch_and_cleans_up() {
        let dir = scratch("copybad");
        let src = dir.join("a.bin");
        let dest = dir.join("out/a.bin");
        write(&src, b"actual content");

        let wrong = "0".repeat(64);
        let err = copy_verified(&src, &dest, &wrong).unwrap_err();
        assert!(matches!(err, FsError::VerificationFailed { .. }));

        assert!(!dest.exists(), "destination must not exist after a failed verify");
        let strays: Vec<_> = std::fs::read_dir(dir.join("out"))
            .unwrap()
            .flatten()
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect();
        assert!(strays.is_empty(), "left behind: {strays:?}");
        assert!(src.exists(), "source must survive a failed copy");
        std::fs::remove_dir_all(dir).ok();
    }

    #[test]
    fn copy_verified_refuses_existing_destination() {
        let dir = scratch("copyexists");
        let src = dir.join("a.bin");
        let dest = dir.join("b.bin");
        write(&src, b"x");
        write(&dest, b"keep me");
        let err = copy_verified(&src, &dest, "whatever").unwrap_err();
        assert!(matches!(err, FsError::DestinationExists { .. }));
        assert_eq!(std::fs::read(&dest).unwrap(), b"keep me");
        std::fs::remove_dir_all(dir).ok();
    }

    #[test]
    fn temp_sibling_stays_in_the_destination_directory() {
        let t = temp_sibling(Path::new("/mnt/share/games/Title (USA).iso"));
        assert_eq!(t.parent(), Path::new("/mnt/share/games").parent().map(|_| Path::new("/mnt/share/games")));
        assert!(t.file_name().unwrap().to_string_lossy().ends_with(".dumo-partial"));
        assert!(t.file_name().unwrap().to_string_lossy().starts_with('.'));
    }

    #[test]
    fn large_content_copies_correctly() {
        let dir = scratch("large");
        let src = dir.join("big.bin");
        let dest = dir.join("big-out.bin");
        let data: Vec<u8> = (0..(3 * 1024 * 1024 + 17)).map(|i| (i % 251) as u8).collect();
        write(&src, &data);

        let expected = hash::sha256_file(&src).unwrap().0;
        copy_verified(&src, &dest, &expected).unwrap();
        assert_eq!(std::fs::read(&dest).unwrap(), data);
        std::fs::remove_dir_all(dir).ok();
    }

    #[test]
    fn write_verified_creates_and_proves_content() {
        let dir = scratch("write-ok");
        let dest = dir.join("sub").join("Game (USA).cue");
        let data = b"FILE \"Game (USA).bin\" BINARY\r\n";
        let want = hash::sha256_of(data);

        let got = write_verified(&dest, data, &want).unwrap();
        assert_eq!(got, want);
        assert_eq!(std::fs::read(&dest).unwrap(), data);
        std::fs::remove_dir_all(&dir).ok();
    }

    /// A wrong expected hash must leave nothing behind — not at the destination, and not
    /// as a stray temp file a later run could mistake for a finished artifact.
    #[test]
    fn write_verified_leaves_nothing_when_the_hash_is_wrong() {
        let dir = scratch("write-bad");
        let dest = dir.join("x.cue");
        let err = write_verified(&dest, b"content", &"0".repeat(64)).unwrap_err();
        assert!(matches!(err, FsError::VerificationFailed { .. }));
        assert!(!dest.exists());
        let leftovers: Vec<_> = std::fs::read_dir(&dir).unwrap().flatten().collect();
        assert!(leftovers.is_empty(), "temp file was left behind");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn write_verified_never_overwrites() {
        let dir = scratch("write-clobber");
        let dest = dir.join("x.cue");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(&dest, b"original").unwrap();

        let data = b"replacement";
        let err = write_verified(&dest, data, &hash::sha256_of(data)).unwrap_err();
        assert!(matches!(err, FsError::DestinationExists { .. }));
        assert_eq!(std::fs::read(&dest).unwrap(), b"original");
        std::fs::remove_dir_all(&dir).ok();
    }
}
